-- adwares テーブル
DROP TABLE IF EXISTS adwares CASCADE;
CREATE TABLE adwares (
  id CHAR(8),
  comment TEXT NOT NULL,
  ad_text VARCHAR(128) NOT NULL,
  category CHAR(8) NOT NULL,
  banner VARCHAR(255),
  banner2 VARCHAR(255),
  banner3 VARCHAR(255),
  banner_m VARCHAR(255),
  banner_m2 VARCHAR(255),
  banner_m3 VARCHAR(255),
  url VARCHAR(255),
  url_m VARCHAR(255),
  url_over VARCHAR(255),
  url_users BOOLEAN NOT NULL DEFAULT FALSE,
  name VARCHAR(128) NOT NULL,
  money VARCHAR(10) NOT NULL,
  ad_type VARCHAR(10) NOT NULL,
  click_money VARCHAR(10) NOT NULL,
  continue_money VARCHAR(10),
  continue_type VARCHAR(10),
  limits INTEGER NOT NULL,
  limit_type CHAR(1) NOT NULL,
  money_count INTEGER DEFAULT 0,
  pay_count INTEGER DEFAULT 0,
  click_money_count INTEGER DEFAULT 0,
  continue_money_count INTEGER DEFAULT 0,
  span INTEGER NOT NULL,
  span_type CHAR(1) NOT NULL,
  use_cookie_interval BOOLEAN DEFAULT FALSE,
  pay_span INTEGER NOT NULL,
  pay_span_type CHAR(1) NOT NULL,
  auto CHAR(1),
  click_auto CHAR(1),
  continue_auto CHAR(1),
  check_type VARCHAR(10) NOT NULL,
  open BOOLEAN DEFAULT FALSE,
  regist BIGINT,
  PRIMARY KEY (id)
);

