services:
  - type: web
    name: asp-orka
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
